### ISSUE TITLE
Cannot auto update plugin

### ISSUE THREAD

**Issue by jonathanbossenger** [fedeandri/bugfu-console-debugger#1]
WordPress thinks the plugin needs to be updated. According to WordPress:

You have version installed. Update to 1.0. View version 1.0 details.

I think that maybe you just need to update the version number somewhere?

**Comment by fedeandri** [comment]
Hey Jonathan thanks and sorry for being late on this, merged and released version 1.1 which adds the possibility to turn off the backtrace info
